<?php

namespace ethercap\apiBase\components;

use yii\base\Model as BaseModel;

class Model extends BaseModel
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }
}
require_once YII2_PATH . '/base/Model.php';
