<?php

namespace ethercap\apiBase;

use ethercap\apiBase\components\Widget;

class ApiRes extends Widget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}
